COQMAKEFILE := CoqMakefile

C_FILE := convex-hull/graham_scan.c
ANDREW_C_FILE := convex-hull/andrew_monotone_chain.c
BASEDIR := convex-hull/ConvexHull
COQ_DEF_FILE := $(BASEDIR)/convex_hull_lib.v

COQ_LIB_FLAGS := \
	-R SeparationLogic/SeparationLogic SimpleC.SL \
	-R SeparationLogic/unifysl Logic \
	-R SeparationLogic/sets SetsClass \
	-R SeparationLogic/compcert_lib compcert.lib \
	-R SeparationLogic/auxlibs AUXLib \
	-R SeparationLogic/examples SimpleC.EE \
	-R SeparationLogic/StrategyLib SimpleC.StrategyLib \
	-R SeparationLogic/Common SimpleC.Common \
	-R SeparationLogic/fixedpoints FP \
	-R SeparationLogic/MonadLib MonadLib \
	-R SeparationLogic/listlib ListLib \
	-R SeparationLogic/MaxMinLib MaxMinLib \
	-R SeparationLogic/GraphLib GraphLib \
	-R SeparationLogic/ConvexHull ConvexHull \
	-R $(BASEDIR) SimpleC.EE.convex_hull

# Generated by symexec from C source
GOAL_V := $(BASEDIR)/graham_scan_goal.v
PROOF_AUTO_V := $(BASEDIR)/graham_scan_proof_auto.v
PROOF_MANUAL_V := $(BASEDIR)/graham_scan_proof_manual.v
GOAL_CHECK_V := $(GOAL_V:_goal.v=_goal_check.v)

ANDREW_GOAL_V := $(BASEDIR)/andrew_monotone_chain_goal.v
ANDREW_PROOF_AUTO_V := $(BASEDIR)/andrew_monotone_chain_proof_auto.v
ANDREW_PROOF_MANUAL_V := $(BASEDIR)/andrew_monotone_chain_proof_manual.v
ANDREW_GOAL_CHECK_V := $(ANDREW_GOAL_V:_goal.v=_goal_check.v)

STRATEGIES_GOAL_V := \
	$(BASEDIR)/point_array_strategy_goal.v \
	$(BASEDIR)/safeexec_strategy_goal.v

STRATEGIES_PROOF_V := \
	$(BASEDIR)/point_array_strategy_proof.v \
	$(BASEDIR)/safeexec_strategy_proof.v

COQ_VFILES := \
	SeparationLogic/ConvexHull/Record_Geo_Vec.v \
	SeparationLogic/ConvexHull/Record_Geo_Point.v \
	SeparationLogic/ConvexHull/Geo_Predicates.v \
	SeparationLogic/ConvexHull/Point_Order.v \
	SeparationLogic/ConvexHull/Point_Array_Specs.v \
	SeparationLogic/ConvexHull/Hull_Equiv.v \
	SeparationLogic/ConvexHull/Graham_Scan.v \
	SeparationLogic/ConvexHull/Graham_Scan_M.v \
	SeparationLogic/ConvexHull/Andrew_Monotone_Chain.v \
	SeparationLogic/ConvexHull/Andrew_Monotone_Chain_M.v \
	SeparationLogic/ConvexHull/Reversal.v \
	SeparationLogic/ConvexHull/ConvexHull.v \
	$(COQ_DEF_FILE) \
	$(STRATEGIES_GOAL_V) \
	$(STRATEGIES_PROOF_V) \
	$(GOAL_V) \
	$(PROOF_AUTO_V) \
	$(PROOF_MANUAL_V) \
	$(GOAL_CHECK_V) \
	$(ANDREW_GOAL_V) \
	$(ANDREW_PROOF_AUTO_V) \
	$(ANDREW_PROOF_MANUAL_V) \
	$(ANDREW_GOAL_CHECK_V)

# Derive .vo targets from earlier path definitions
VC_TARGETS := \
	$(STRATEGIES_PROOF_V:.v=.vo) \
	$(PROOF_AUTO_V:.v=.vo) \
	$(PROOF_MANUAL_V:.v=.vo) \
	$(GOAL_CHECK_V:.v=.vo)

QUICK_TARGETS := $(VC_TARGETS:.vo=.vos)
VOK_TARGETS := $(VC_TARGETS:.vo=.vok)

ANDREW_VC_TARGETS := \
	SeparationLogic/ConvexHull/Andrew_Monotone_Chain.vo \
	SeparationLogic/ConvexHull/Andrew_Monotone_Chain_M.vo \
	$(ANDREW_GOAL_V:.v=.vo) \
	$(ANDREW_PROOF_AUTO_V:.v=.vo) \
	$(ANDREW_PROOF_MANUAL_V:.v=.vo) \
	$(ANDREW_GOAL_CHECK_V:.v=.vo)

.DEFAULT_GOAL := build

.PHONY: all build quick vok-check all-vfiles clean distclean deps symexec andrew-symexec andrew-build

all: build

build: symexec andrew-symexec deps
	$(MAKE) -f $(COQMAKEFILE) $(VC_TARGETS) $(ANDREW_VC_TARGETS)

quick: symexec deps
	$(MAKE) -f $(COQMAKEFILE) $(QUICK_TARGETS)

vok-check: symexec deps quick
	$(MAKE) -f $(COQMAKEFILE) $(VOK_TARGETS)

# --- Symexec: regenerate Coq VC files from C source ---
SYMEXEC := symexec
SYMEXEC_STRATEGY_DIR := $(abspath convex-hull)/
SYMEXEC_INPUT_FILE := $(abspath $(C_FILE))
SYMEXEC_FLAGS := \
	--coq-logic-path=SimpleC.EE.convex_hull \
	-slp $(SYMEXEC_STRATEGY_DIR) SimpleC.EE.convex_hull \
	--no-exec-info

SYMEXEC_OUTPUTS := $(GOAL_V) $(PROOF_AUTO_V) $(GOAL_CHECK_V)
ANDREW_SYMEXEC_OUTPUTS := $(ANDREW_GOAL_V) $(ANDREW_PROOF_AUTO_V) $(ANDREW_GOAL_CHECK_V)
SYMEXEC_UPDATE_MANUAL ?= 0
symexec: $(SYMEXEC_OUTPUTS)
andrew-symexec: $(ANDREW_SYMEXEC_OUTPUTS)

# Grouped target (&:)
$(SYMEXEC_OUTPUTS) &: $(C_FILE)
	$(SYMEXEC) \
	  --goal-file=$(GOAL_V) \
	  --proof-auto-file=$(PROOF_AUTO_V) \
	  --proof-manual-file=$(PROOF_MANUAL_V) \
	  $(SYMEXEC_FLAGS) \
	  --input-file=$(SYMEXEC_INPUT_FILE) \

$(ANDREW_SYMEXEC_OUTPUTS) &: $(ANDREW_C_FILE)
	$(SYMEXEC) \
	  --goal-file=$(ANDREW_GOAL_V) \
	  --proof-auto-file=$(ANDREW_PROOF_AUTO_V) \
	  --proof-manual-file=$(ANDREW_PROOF_MANUAL_V) \
	  $(SYMEXEC_FLAGS) \
	  --input-file=$(abspath $(ANDREW_C_FILE)) \

andrew-build: andrew-symexec deps
	$(MAKE) -f $(COQMAKEFILE) $(ANDREW_VC_TARGETS)

all-vfiles: symexec andrew-symexec deps

clean: deps
	$(MAKE) -f $(COQMAKEFILE) clean

distclean:
	@if [ -f "$(COQMAKEFILE)" ]; then $(MAKE) -f $(COQMAKEFILE) clean; fi
	$(RM) $(COQMAKEFILE) $(COQMAKEFILE).conf .$(COQMAKEFILE).d _CoqProject
	$(RM) **.{vo,vos,vok,glob,aux}

deps: $(COQMAKEFILE)

$(COQMAKEFILE): _CoqProject
	coq_makefile -f _CoqProject -o $(COQMAKEFILE)

_CoqProject: Makefile
	@echo $(COQ_LIB_FLAGS) $(COQ_VFILES) > _CoqProject
