COQMAKEFILE := CoqMakefile

C_FILE := convex-hull/graham_scan.c
BASEDIR := convex-hull/ConvexHull

COQ_LIB_FLAGS := \
	-R SeparationLogic/SeparationLogic SimpleC.SL \
	-R SeparationLogic/unifysl Logic \
	-R SeparationLogic/sets SetsClass \
	-R SeparationLogic/compcert_lib compcert.lib \
	-R SeparationLogic/auxlibs AUXLib \
	-R SeparationLogic/examples SimpleC.EE \
	-R SeparationLogic/StrategyLib SimpleC.StrategyLib \
	-R SeparationLogic/Common SimpleC.Common \
	-R SeparationLogic/fixedpoints FP \
	-R SeparationLogic/MonadLib MonadLib \
	-R SeparationLogic/listlib ListLib \
	-R SeparationLogic/MaxMinLib MaxMinLib \
	-R SeparationLogic/GraphLib GraphLib \
	-R SeparationLogic/ConvexHull ConvexHull \
	-R $(BASEDIR) SimpleC.EE.convex_hull

# Generated by symexec from C source
GOAL_V := $(BASEDIR)/graham_scan_goal.v
PROOF_AUTO_V := $(BASEDIR)/graham_scan_proof_auto.v
PROOF_MANUAL_V := $(BASEDIR)/graham_scan_proof_manual.v
GOAL_CHECK_V := $(GOAL_V:_goal.v=_goal_check.v)

STRATEGIES_GOAL_V := \
	$(BASEDIR)/point_array_strategy_goal.v \
	$(BASEDIR)/safeexec_strategy_goal.v

STRATEGIES_PROOF_V := \
	$(BASEDIR)/point_array_strategy_proof.v \
	$(BASEDIR)/safeexec_strategy_proof.v

COQ_VFILES := \
	$(BASEDIR)/convex_hull_lib.v \
	$(STRATEGIES_V) \
	$(GOAL_V) \
	$(PROOF_AUTO_V) \
	$(PROOF_MANUAL_V) \
	$(GOAL_CHECK_V)

# Derive .vo targets from earlier path definitions
VC_TARGETS := \
	$(STRATEGIES_PROOF_V:.v=.vo) \
	$(PROOF_AUTO_V:.v=.vo) \
	$(PROOF_MANUAL_V:.v=.vo) \
	$(GOAL_CHECK_V:.v=.vo)

.DEFAULT_GOAL := build

.PHONY: all build all-vfiles clean distclean deps symexec

all: build

build: symexec deps
	$(MAKE) -f $(COQMAKEFILE) $(VC_TARGETS)

# --- Symexec: regenerate Coq VC files from C source ---
SYMEXEC := symexec
SYMEXEC_FLAGS := \
	--coq-logic-path=SimpleC.EE.convex_hull \
	-slp convex-hull/ SimpleC.EE.convex_hull \
	--no-exec-info

symexec: $(GOAL_V) $(PROOF_AUTO_V) $(PROOF_MANUAL_V)

# Grouped target (&:)
$(GOAL_V) $(PROOF_AUTO_V) $(PROOF_MANUAL_V) &: $(C_FILE)
	$(SYMEXEC) \
	  --goal-file=$(GOAL_V) \
	  --proof-auto-file=$(PROOF_AUTO_V) \
	  --proof-manual-file=$(PROOF_MANUAL_V) \
	  $(SYMEXEC_FLAGS) \
	  --input-file=$(C_FILE)

all-vfiles: symexec deps

clean: deps
	$(MAKE) -f $(COQMAKEFILE) clean

distclean:
	@if [ -f "$(COQMAKEFILE)" ]; then $(MAKE) -f $(COQMAKEFILE) clean; fi
	$(RM) $(COQMAKEFILE) $(COQMAKEFILE).conf .$(COQMAKEFILE).d _CoqProject

deps: $(COQMAKEFILE)

$(COQMAKEFILE): _CoqProject
	coq_makefile -f _CoqProject -o $(COQMAKEFILE)

_CoqProject:
	@echo $(COQ_LIB_FLAGS) $(COQ_VFILES) > _CoqProject
